[package]
name = "kael"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.6", features = ["cargo"] }
kael-helpers = { path = "../../shared/kael-helpers" }
kael-logger = { path = "../../shared/kael-logger" }
kael-bili = { path = "../../commands/kael-bili" }
