[package]
name = "kael-bili"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
duct = "0.13.6"
fs_extra = "1.3.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
kael-logger = { path = "../../shared/kael-logger" }
